services:
  postgres_zingstreamp3:
    image: postgres:12
    hostname: postgres_zingstreamp3
    container_name: postgres_zingstreamp3
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=zingstreamp3
      - POSTGRES_PORT=5433
      - POSTGRES_HOST=postgres
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - ./postgres_zingstreamp3:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    networks:
      - zingstreamp3

networks:
  zingstreamp3:
    driver: bridge
    name: zingstreamp3