mydbt:
  outputs:
    dev:
      type: redshift
      host: "zingstreamp3-20240712.clwvssorqis4.us-east-1.redshift.amazonaws.com"
      user: "huynhdoanho"
      password: "DoanHo1112."
      port: 5439
      dbname: "dev"
      schema: "marts"
      threads: 4
      region: "us-east-1"

    staging:
      type: redshift
      host: "zingstreamp3-20240712.clwvssorqis4.us-east-1.redshift.amazonaws.com"
      user: "huynhdoanho"
      password: "DoanHo1112."
      port: 5439
      dbname: "dev"
      schema: "staging"
      threads: 4
      region: "us-east-1"

  target: dev