-- -- tạo spectrum schema:
-- CREATE EXTERNAL SCHEMA IF NOT EXISTS spectrum_schema
-- FROM DATA CATALOG DATABASE 'zingstreamp3'
-- IAM_ROLE 'arn:aws:iam::891377228605:role/MySpectrumRole'
-- CREATE EXTERNAL DATABASE IF NOT EXISTS;

CREATE EXTERNAL SCHEMA IF NOT EXISTS spectrum_schema
FROM DATA CATALOG
DATABASE 'dev'
IAM_ROLE 'arn:aws:iam::891377228605:role/MySpectrumRole'
CREATE EXTERNAL DATABASE IF NOT EXISTS;